### ISSUE TITLE
@mixin: graceful degradation for font-size

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#1]
```scss
$normal-font-size: 16px;
$root-font-size: $normal-font-size * 62.5%;

function rem2px($rem, $base-font-size: $root-font-size) {
  @if unitless($rem) {
    @warn 'Assuming #{$rem} to be in rems, attempting to convert it into rems.';
    @return rem2px($rem + 0rem);
  } @else if unit($rem)  == px {
    @return $rem;
  }

  return $base-font-size * $ rem;
}

@mixin font-size($rem) {
  font-size: rem2px($rem);
  font-size: $rem;
}
```
