### ISSUE TITLE
base: animation @keyframes

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#16]
```css
/* transform-origin: top center */
@keyframes fold-flip {
  0% {
    opacity: 0;
    transform: rotateX(-90deg);
  }
  60% {
    transform: rotateX(50deg)
  }
  100% {
    opacity: 1;
    transform: rotateX(0);
  }
}
/* transform-origin: top center */
@keyframes horizonal-rotate-in {
  0% {
    opacity: 0;
    transform: rotateY(-90deg) translateY(30px);
  }
  100% {
    opacity: 1;
    transform: rotateY(0) translateY(0);
  }
}
/* transform-origin: top center */
@keyframes bounce-in {
  0% {
    opacity: 0;
    transform: scale(0.5) translateY(-30px);
  }
  80% {
    opacity: 1;
    transform: scale(1.2);
  }
  100% {
    opacity: 1;
    transform: rotateY(0) translateY(0);
  }
}
/* transform-origin: top right */
@keyframes rotate-right-in {
  0% {
    opacity: 0;
    transform: rotate(-30deg) translateX(30px);
  }
  100% {
    opacity: 1;
    transform: rotate(0) translateX(0);
  }
}
```

**Comment by sabertazimi** [comment]
```css
@keyframes tooltip {
  0% {
    opacity: 0;
    transform: scale(0.1) rotate(30deg) translateY(50px) rotateX(90deg);
  }
  50% {
    opacity: 1;
    transform: rotate(-10deg) rotateX(-2deg);
  }
  70% {
    transform: rotate(3deg);
  }
  100% {
    transform: scale(1);
  }
}
```

**Comment by sabertazimi** [comment]
```css
// origin opacity is 0
@keyframes pulse {
  0% {
    transform: scale(0)
    opacity: 1
  }
  100% {
    transform: scale(1.3)
    opacity: 0
  }
}
```

**Comment by sabertazimi** [comment]
```css
@keyframes spinny {
  0% {
    transform: rotate(0deg) scale(1);
  }
  50% {
    transform: rotate(45deg) scale(1.2);
  }
  100% {
    transform: rotate(360deg) scale(1);
  }
}
```

**Comment by sabertazimi** [comment]
```sass
@keyframes fall-down-out
  0%
    transform: translateY(0px) rotate(0deg)
  60%
    transform: rotate(60deg)
  100%
    transform: translateY(800px) rotate(10deg)
```

**Comment by sabertazimi** [comment]
```sass
@keyframes fold-in
  0%
    opacity: 0
    transform: rotateX(-90deg)
  100%
    opacity: 1
    transform: rotateX(0deg)
```

**Comment by sabertazimi** [comment]
```css
@keyframes fade-in-out {
  0% {
    opacity: 0
  }
  50% {
    opacity: 1
  }
  100% {
    opacity: 0
  }
}
```

**Comment by sabertazimi** [comment]
link hover animation

```css
a {
    text-decoration: none;
    background-image: linear-gradient(currentColor, currentColor);
    background-position: 0% 100%;
    background-repeat: no-repeat;
    background-size: 0% 2px;
    transition: background-size .3s;
}

a:hover {
    background-size: 100% 2px;
}
```

**Comment by sabertazimi** [comment]
```css
@keyframes radial-pulse {
  0% {
    box-shadow: 0 0 0 0px rgba(0, 0, 0, 0.5);
  }

  100% {
    box-shadow: 0 0 0 30px rgba(0, 0, 0, 0);
  }
}
```
