### ISSUE TITLE
components: _button.scss

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#2]
```scss
// Configuration
$btn-name: 'button' !default;
$btn-size-ratio: 1.2 !default;
$btn-hover: 25% !default;
$btn-border: 20% !default;
$btn-background: (
    'default': #565656,
    'success': #468847,
    'danger': #b94a48,
    'warning': #c09853,
    'info': #3a87ad
  ) !default;

@mixin button-color($color) {
  background-color: $color;

  @include on-event {
    background: saturate($color, $btn-hover);
  }

  @if $btn-border {
    border-color: darken($color, $btn-border);
  }
}

.#{$btn-name} {
  // Default styles
  padding: 0.5em;
  margin-bottom: 1em;
  color: #fff;

  // Some sex appeal!
  transition: background 0.15s;
  border-radius: 0.15em;
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.15);

  // Border or not border?
  border: if($btn-border, 1px solid, none);

  // Modifiers
  &--large {
    font-size: 1em * $btn-size-ratio;
  }

  &--small {
    font-size: 1em / $btn-size-ratio;
  }

  &--bold {
    font-weight: bold;
  }

  &--upper {
    text-transform: uppercase;
  }

  &--block {
    display: block;
    width: 100%;
  }

  // Color schemes
  @each $key, $value in $btn-background {
    &--#{$key} {
      @include button-color($value);
    }
  }
}
```
