### ISSUE TITLE
component: shadow-button

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#20]
.btn--shadow

**Comment by sabertazimi** [comment]
Use hsl for color button:

```css
:root {
  --primary-h: 221;
  --primary-s: 72%;
  --primary-l: 62%;
}

.button {
  background-color: hsl(var(--primary-h), var(--primary-s), var(--primary-l));
}

.button--secondary {
    --primary-l: 90%;
    color: #222;
}

.button--ghost {
    --primary-l: 90%;
    background-color: transparent;
    border: 3px solid hsl(var(--primary-h), var(--primary-s), var(--primary-l)); 
}
```
