### ISSUE TITLE
base: svg icon

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#22]
## Resources

- https://nucleoapp.com/
- https://blog.nucleoapp.com/the-guide-to-integrating-and-styling-icon-systems-inline-svg-and-icon-components-9ed234419166
- https://icomoon.io/app/#/select
- https://github.com/davidkpiano/sass-svg
- https://icons8.cn/

## Principles

- if the fill attribute is defined (and is different from “none”), remove it from the element;
- if the stroke attribute is defined (and is different from “none”), replace it with stroke=”currentColor”, so that can set its value in CSS using the color property;
- add the fill attribute only to the SVG element

```scss
svg {
  color: blue; //this will target the stroke
  fill: red; //this will target the fill
}

svg.theme-dark {
  color: #fff;
}
svg.theme-light {
  color: #000;
}

svg.stroke-4 {
  stroke-width: 4;
}
```

## Implementation

- font-size
- color
- alignment

```scss

:root {
  --icon-xs: 16px;
  --icon-sm: 24px;
  --icon-md: 32px;
  --icon-lg: 48px;
  --icon-xl: 64px;
}

/* icon size */
.icon--xs {
  font-size: var(--icon-xs);
}

.icon--sm {
  font-size: var(--icon-sm);
}

.icon--md {
  font-size: var(--icon-md);
}

.icon--lg {
  font-size: var(--icon-lg);
}

.icon--xl {
  font-size: var(--icon-xl);
}
```

```scss
.icon {
  display: inline-block;
  color: var(--color-icon-primary);
  height: 1em;
  width: 1em;
  line-height: 1;
}
```

```scss
.icon-text-aligner {
  display: flex;
  align-items: center;

  > *:nth-child(2) {
    margin-left: var(--space-xxs);
  }

  .icon {
    color: inherit;
    flex-shrink: 0;
  }
}
```

## SVG Sprites

- can’t edit colors in CSS
- adding/removing icons would be tricky
- image sprites cannot change along with font size

```scss
.icon {
    display: inline-block;
    height: 96px;
    width: 96px;
    background-image: url(../icons.svg);
    background-repeat: no-repeat;
}

.icon.icon-check {
    background-position: -0px -0px;
}

.icon.icon-tags {
    background-position: -96px -0px;
}

.btn-download::before {
    content: '';
    display: inline-block;
    height: 16px;
    width: 16px;
    background-image: url(../icons-16.svg);
    background-repeat: no-repeat;
    background-position: -16px 0px;
    vertical-align: middle;
    margin-right: 0.25em;
}
```

```scss
$icon-sm: 16px;
$icon-md: 32px;
$icon-lg: 64px;
.icon {
    display: inline-block;
    background-repeat: no-repeat;
}
@mixin icon-sm {
    width: $icon-sm;
    height: $icon-sm;
    background-image: url(../assets/icons-sm.svg);
}
@mixin icon-md {
    width: $icon-md;
    height: $icon-md;
    background-image: url(../assets/icons-md.svg);
}
@mixin icon-lg {
    width: $icon-lg;
    height: $icon-lg;
    background-image: url(../assets/icons-lg.svg);
}
.icon--sm {
    @include icon-sm;
}
.icon--md {
    @include icon-md;
}
.icon--lg {
    @include icon-lg;
}
// icon classes
.icon--check {
    background-position: 0 0;
}
.icon--settings {
    background-position: -16px 0;
}
```

## SVG Symbol

```scss
<svg style="display: none;">
  <symbol viewBox="0 0 48 48" id="skull">
    <title>skull</title>
    <path d=".." fill="none" stroke="#444" stroke-width="2"/>
  </symbol>
</svg>

<body>
  <svg><use href="#skull" xlink:href="#skull"/></svg>
</body>
```

```scss
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol viewBox="0 0 48 48" id="skull">
    <title>skull</title>
    <path d=".." fill="none" stroke="#444" stroke-width="2"/>
  </symbol>
  <symbol viewBox="0 0 32 32" id="check">
    <title>check</title>
    <path d=".." fill="none" stroke="#444" stroke-width="2"/>
  </symbol>
  <symbol viewBox="0 0 48 48" id="home">
    <title>home</title>
    <path d=".." fill="none" stroke="#444" stroke-width="2"/>
  </symbol>
</svg>

<body>
  <svg><use href="assets/icons.svg#skull" xlink:href="assets/icons.svg#skull"/></svg>
</body>

```
