### ISSUE TITLE
animation: hover effect

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#26]
```css
a {
	padding: 5px; 
	display: inline-block;
	text-decoration: none; 
	transition: all 0.3s;
	background-size: 100% 200%; 
	background-image: linear-gradient(to top, #333 50%, #fff 50%); 
	color: #333;
	}
a:hover { 
	background-position: 0 100%; 
	color: #fff; 
	}
```

## Demos

https://github.com/sampotts/plyr
