### ISSUE TITLE
mixins: background-linear-gradient

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#6]
```scss
@mixin linear-gradient($direction, $gradients...) {
  background-color: nth($gradients, 1);
  background-image: linear-gradient($direction, $gradients...);
}
```
