### ISSUE TITLE
base: modular font-size container

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/mass#8]
update `base/_typography.scss` section of `text size`

```scss
.text-container {
  font-size: 1.2rem;
}

.text-container p {
  font-size: 1em;
}

article {
  font-size: 1.2rem;
}

article p {
  font-size: 1em;
}
```
